### ISSUE TITLE
Tutorial issue

### ISSUE THREAD

**Issue by craiggrummitt** [ParsePlatform/ParseUI-iOS#100]
This issue is related to the tutorial "Integrating with Facebook", section "Bypassing the Login."
https://github.com/ParsePlatform/ParseUI-iOS/wiki/Integrate-Login-with-Facebook

I'm writing regarding the following text and code snippet:

> ...if the user is not logged in - simpy present the login view controller.

```
if ([PFUser currentUser] && // Check if user is cached
        [PFFacebookUtils isLinkedWithUser:[PFUser currentUser]]) { // Check if user is linked to Facebook

        PFLogInViewController *controller = [[PFLogInViewController alloc] init];
...
    }
```

I may be misunderstanding, but shouldn't we be taking the user to a loginViewController if the current user is **NOT** linked to Facebook?

**Comment by nlutsenko** [comment]
Haha - awesome catch.
Also, congrats on issue #100 :+1: 

Feel free to send a PR to fix it there.

**Comment by craiggrummitt** [comment]
Cheers, have made the change. (Not sure why, but didn't require a PR)

**Comment by nlutsenko** [comment]
Oops. Now it will. Many thanks for updating it! Closing this issue.
