### ISSUE TITLE
How to cope with declined permissions?

### ISSUE THREAD

**Issue by Ricardo1980** [ParsePlatform/ParseUI-iOS#102]
Hello!
When a user logins into my system using facebook, I want to take his email and birthdate and save in into the User table.
I see PFLogInViewController has a field called "facebookPermissions". But with new facebook API SDK (4.0) user can decline specific permissions and accept others.
What I want to do is if user decline to give me his birthdate or email, then tell him it is mandatory in my system for several reasons and the run the login process again. 
That's easy with facebook ios sdk, using:

```
FBSDKLoginManager *login = [[FBSDKLoginManager alloc] init];
[login logInWithReadPermissions:@[@"email"] handler:^(FBSDKLoginManagerLoginResult *result, NSError *error) {
  if (error) {
    // Process error
  } else if (result.isCancelled) {
    // Handle cancellations
  } else {
    // If you ask for multiple permissions at once, you
    // should check if specific permissions missing
    if ([result.grantedPermissions containsObject:@"email"]) {
      // Do work
    } else {
    // tell the user I really need that
    }
  }
}];
```

How should I manage facebook permissions when using ParseUI rather than facebook SDK alone? Specially the case where user declines several of them.
Thanks a lot.

**Comment by DanielsCode** [comment]
I have the same challenge ... any idea?

**Comment by nlutsenko** [comment]
Hmm...
Since Parse just wraps FBSDK inside PFLogInViewController (you can see from the code) - you can simply put this logic inside a delegate method on `PFLogInViewController`.
The end result would look like something like this:

```objc
- (void)logInViewController:(PFLogInViewController *)logInController didLogInUser:(PFUser *)user {
    NSSet *grantedPermissions = [FBSDKAccessToken currentAccessToken].permissions;
    if ([grantedPermissions containsObject:@"email"]) {
        // Do work
        [self dismissViewControllerAnimated:YES completion:nil]; // Dismiss the LogInViewController
    } else {
        // Tell the user that you really need that.
    }
}
```

I hope this helps. Feel free to reopen the issue if you have any questions or concerns about using this approach.

**Comment by Ricardo1980** [comment]
Thanks for reply. I will do that. Just one more question.
If the user doesn't give me a specific permission that I need it for my app, can I show a message there a dialog telling you should grant that permission (and the reason) and then close the parse session in order to let the user try again?

**Comment by nlutsenko** [comment]
Tbh, I would recommend avoiding that flow, as in my personal view it is slightly suboptimal user experience.
But if you want it - yes, showing an alert view with text on why you need it and logging the user out (via `[PFUser logOut]` is the way to go.
