### ISSUE TITLE
Update to Swift 2.0

### ISSUE THREAD

**Issue by krishaamer** [ParsePlatform/ParseUI-iOS#104]
Hi, I'm getting errors in Xcode 7. Do you have plans to update to Swift 2.0?

Thanks,
Kris

**Comment by nlutsenko** [comment]
Hey Kris,

Absolutely! We do have a plan for updating the code here for Swift 2.0. The only thing that's tricky right now is backward compatibility. Not everyone is running the latest beta of Xcode and we still want to be 100% backward compatible.

I think one of the ways we are going to achieve this is by using a custom branch specifically for Swift 2.0 stuff.

**Comment by nickswalker** [comment]
+1. Would appreciate a Swift 2.0 branch.

**Comment by rogernolan** [comment]
@krishaamer what errors are you seeing? I just updated the whole repo using the automated migration tool and there aren't any issues - a few warnings but nothing that would stop you building with Swift 2.0

I do see a problem linking against a bitcode enabled target (the default for Xcode 7) but that's not a swift issue.
