### ISSUE TITLE
Update Facebook Login tutorial

### ISSUE THREAD

**Issue by will83** [ParsePlatform/ParseUI-iOS#107]
Is it possible to update the Facebook Login tutorial in swift with the latest version of the Facebook sdk? Thanks

**Comment by nlutsenko** [comment]
Hey @will83, sorry it took that much time to get to this issue.
Are you talking about this one https://github.com/ParsePlatform/ParseUI-iOS/wiki/Integrate-Login-with-Facebook ?

There is a full-working demo available in ParseUIDemo-Swift, it might help you get started.
(https://github.com/ParsePlatform/ParseUI-iOS/tree/master/ParseUIDemo/Swift)
Is there anything specific you are looking for?

(I am going to close this issue for now, but feel free to reopen at any time)
