### ISSUE TITLE
CI fails for updated UI-Parse Pull #97

### ISSUE THREAD

**Issue by mmarshak** [ParsePlatform/ParseUI-iOS#109]
Hi Guys,

I corrected the comments you provided me for the addition of the first name & last name.
I use now First name and Family name, as well I address the other comments.

However the CI is failing all the time, is is compelling about PFImageView and PFFile, see bellow the error.
I did not change any of those files.
I do not know how to figure out what is wrong . I also not sure how to see the output of ‘verbose’.
Could you help me to figure out what is wrong ?

Thanks,
Marik Marshak

The command "pod lib lint --quick ParseUI.podspec" exited with 0.
11.00s$ pod lib lint --use-libraries ParseUI.podspec
 -> ParseUI (1.1.4)
    - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS]  /Users/travis/build/ParsePlatform/ParseUI-iOS/ParseUI/Classes/Views/PFImageView.m:26:9: fatal error: 'Parse/PFFile.h' file not found
[!] ParseUI did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
The command "pod lib lint --use-libraries ParseUI.podspec" exited with 1.
0.00s$ set -o pipefail

**Comment by nlutsenko** [comment]
Looking into the problem right now. Just restarted the build on #97 
It cleanly passes for me on 10.10.4 with Xcode 6.4.
I really suspect a transient failure.

**Comment by mmarshak** [comment]
Hi Nikita ,

Thank you, this is great news.

Could you also approve my pull request ?

Thanks,
Marik


On Jul 6, 2015, at 3:41 PM, Nikita Lutsenko <notifications@github.com> wrote:

Looking into the problem right now. Just restarted the build on #97 
It cleanly passes for me on 10.10.4 with Xcode 6.4.
I really suspect a transient failure.

**Comment by nlutsenko** [comment]
Sure, I just merged an update for the configuration. Let me restart the build on #97.

**Comment by mmarshak** [comment]
Thanks !

Marik


On Jul 6, 2015, at 4:00 PM, Nikita Lutsenko <notifications@github.com> wrote:

Sure, I just merged an update for the configuration. Let me restart the build on #97.

**Comment by mmarshak** [comment]
Hi Nikita,

I saw you commented -

>>> Can you please rebase the branch on the latest master and squash everything into a single commit?
I understand you want to to update my code with the latest master. However what you mean by ‘squash everything to a single commit’ ? 
I am not expert with github, by my understanding that if I update my local repository with the latest master then I do not need to submit a new pull request.
Can you provide some guidance what I need to do ?

Marik

**Comment by mmarshak** [comment]
HI

Ok, I did the rebase and the squashing. I hop I did it correctly.
Please let me know if you are all set to complete this pull request. I really will love to get over with this pull request.

Thank you for helping me out.

Thanks,
Marik
