### ISSUE TITLE
How to show class rows to PFQueryTableView squeezed with whereKey

### ISSUE THREAD

**Issue by tomojiro1125** [ParsePlatform/ParseUI-iOS#113]
I could show all PFUser class in PFQueryTableView like below code.

- (id)initWithStyle:(UITableViewStyle)style {
    self = [super initWithStyle:style];
    self = [super initWithClassName:@"_User"];
    
    if (self) {
        self.parseClassName = @"_User";
    }
    return self;
}

I can get all rows in PFUser class,
but I want to squeeze User as PFQuery uses whereKey.
How should I squeeze User in PFQueryTableViewController ?
If I can't, I am planning to use just UITableViewController.

**Comment by tomojiro1125** [comment]
I solved this issue.
I used it in queryForTable, thx

**Comment by rinyfo4** [comment]
@tomojiro1125 how did you use it in queryForTable? Mind posting that function?

**Comment by rinyfo4** [comment]
Got it:  


    override func queryForTable() -> PFQuery {
        var query : PFQuery = PFUser.query()!
        
        if(objects?.count == 0) {
          
            query.cachePolicy = PFCachePolicy.CacheElseNetwork
        
        }
        
        query.whereKey("contacts", containedIn: contactsNeeded)
        
        return query
    }
