### ISSUE TITLE
Notifications in Swift Starter

### ISSUE THREAD

**Issue by sitver** [ParsePlatform/ParseUI-iOS#119]
The following code from the Swift Starter is giving me trouble in Swift 2.0. The Error is "The Binary Operator "|" cannot be applied to two":

/*if application.respondsToSelector("registerUserNotificationSettings:") {
            let userNotificationTypes = UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound
        
            let settings = UIUserNotificationSettings(forTypes: userNotificationTypes, categories: nil)
            application.registerUserNotificationSettings(settings)
            application.registerForRemoteNotifications()
        } else {
            let types = UIRemoteNotificationType.Badge | UIRemoteNotificationType.Alert | UIRemoteNotificationType.Sound
            application.registerForRemoteNotificationTypes(types)
        }*/

**Comment by bre7** [comment]
You need to use OptionSetType:
```swift
let types = [
    UIRemoteNotificationType.Badge,
    UIRemoteNotificationType.Alert,
    UIRemoteNotificationType.Sound
]
```

When you open the project in Xcode7, you should use the Swift 2 Migrator.
