### ISSUE TITLE
Compile error when using Parse 1.7.5.3 and ParseUI 1.1.4

### ISSUE THREAD

**Issue by hpogosyan** [ParsePlatform/ParseUI-iOS#124]
Getting a compile error on a working project when I add ParseUI to my Podfile:

  	pod 'Parse', '~> 1.7'
  	pod 'ParseUI', '~> 1.1.4'
	pod 'TwilioSDK', '~> 1.2'
	pod 'Testfire', '~> 1.3.1'
	pod 'libPhoneNumber-iOS', '~> 0.8'
	pod 'JVFloatLabeledTextField'

Here is the error in Xcode 6.4 on OS X 10.10.4

	clang: error: no such file or directory: 'dynamic_lookup'
	clang: error: no such file or directory: 'suppress'

@davidvardan

**Comment by nlutsenko** [comment]
Hey @hpogosyan, I've just tested this configuration and it works great with the latest ParseUI 1.1.5 and Parse 1.8.0 that are available since today.
Let me know if there is anything else I can help you with.
