### ISSUE TITLE
Compile error when using Parse 1.8.0 and ParseUI 1.1.4

### ISSUE THREAD

**Issue by dpreston10** [ParsePlatform/ParseUI-iOS#125]
PFSignUpViewController.m and PFLoginViewController.m both have compile errors of Semantic Issue Use of undeclared identifier 'PFUIAlertView'.

.

**Comment by fatuhoku** [comment]
+1 getting this as well, on `PFProductTableViewController` too.

**Comment by nlutsenko** [comment]
Looking into it. Will have a solution shortly.

**Comment by reidmweber** [comment]
PFLogInViewController.m is also broken on:
#import <Parse/PFTwitterUtils.h>
since TwitterUtils is no longer included with Parse in 1.8.0

**Comment by apersaud** [comment]
+1. According to the Change log for the Parse SDK, `ParseTwitterUtils` is a separate framework, however even including this as a cocoapod, the 1.1.4 version is not referencing it correctly.

**Comment by MartinHerman** [comment]
+1

**Comment by nlutsenko** [comment]
ParseUI 1.1.5 is out on CocoaPods.
Let me know guys if you run into any more problems.

**Comment by reidmweber** [comment]
:+1: That fixed it for me. Thanks

**Comment by dpreston10** [comment]
thank you ...all compiled now

**Comment by fatuhoku** [comment]
:beers:
