### ISSUE TITLE
PFLogInViewController: no Facebook button with emailAsUserName

### ISSUE THREAD

**Issue by FredddyF** [ParsePlatform/ParseUI-iOS#130]
I suppose it's because of my Swift implementation, but I can't have the Facebook button appear in the PFLogInViewController.
This is not due to FB integration, since using only the standard FB login button instead of a PFLogInViewController works perfectly.

Looking in StackOverflow, it appears I'm not the only one with this issue.

**Comment by FredddyF** [comment]
OK, got it.
There is no issue with Swift, actually.
The Facebook login seems to be incompatible with emailAsUserName.

So if I set this :
    loginViewController.emailAsUsername = true
the "Log In with Facebook" button disappears.

I don't know if this is a bug or working as designed.

**Comment by nlutsenko** [comment]
Sounds like a bug, definetly.
I'll investigate and update this issue shortly.

**Comment by FredddyF** [comment]
Cool, thanks !
I updated the title to show the actual issue.
Fred

**Comment by nlutsenko** [comment]
Hey @FredddyF, I think I found the issue that you are experiencing.
Try moving `.emailAsUsername = true` to after you set `fields` on `PFLogInViewController`.
The setter triggers load of PFLogInView, which captures the state of `fields` property, thus making it impossible to change it after they are set.

This is definitely something we would want to avoid, I am going to send a Pull Request to fix the problem at it's source.

**Comment by FredddyF** [comment]
Hi Nikita!

I set the emailAsUsername line after the fields, and that works perfectly now. Thanks a lot!
Cheers to your reactivity!

Have a good day
Fred
