### ISSUE TITLE
PFLoginViewController: attempt to present UIAlertController outside window hierarchy

### ISSUE THREAD

**Issue by muccy** [ParsePlatform/ParseUI-iOS#134]
Hi,
I'm using PFLoginViewController with Facebook and Twitter login buttons. I have multiple accounts set on my phone and I suppose an action sheet is presented on root view controller causing this error:

````
Attempt to present <UIAlertController: 0x15dd56b70> on <UITabBarController: 0x15dd137e0> whose view is not in the window hierarchy
````

Looking at code I understand the problem is inside `-[PFTwitterUtils logInWithBlock:]`.
I'm trying to circumvent the problem by rewriting the entire Twitter login phase not using that method but I don't think it would be a real solution to the problem.

You can reproduce the same issue with ParseUI demo app.

**Comment by nlutsenko** [comment]
Hey @muccy, this was already resolved in the latest master of [Parse-SDK](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX) and should be out with the next release.
You can start using master right now to fix the problem.

**Comment by muccy** [comment]
Using `pod 'Parse', :head` fixed the issue. Thanks.
