### ISSUE TITLE
Strings not localized when ParseUI is integrated as framework

### ISSUE THREAD

**Issue by ciryon** [ParsePlatform/ParseUI-iOS#136]
I'm trying to add localization to ParseUI components.

When I run this code from my AppDelegate it works and text is successfully translated to Swedish:

` let s = NSLocalizedString("Loading...", comment: "Loading message of PFQueryTableViewController")`

When the same code is run in PFLoadingView.m on line 46 the localization is still English. It seems that code in ParseUI can't find my Localizable.strings somehow.

I'm using Parse and ParseUI with CocoaPods (with use_frameworks!) and my main project uses Swift and base iOS SDK version 8.1. I've also tried to manually download the framework files and integrate them as per ParseUI documentation, but still doesn't work.

I've tried using ParseUI 1.1.5 and latest from git.

**Comment by nlutsenko** [comment]
And I think you are right, it doesn't quite work, since we are always looking for the strings in the main bundle, but the strings actually should be in the framework bundle.

Marking for next version, so we can address it quickly.

**Comment by ciryon** [comment]
I'm still not getting this to work. I saw that you now keep the strings in a table called "ParseUI". If I'm doing this correctly I should put my strings (in a file called ParseUI.strings) in order for your code to pick it up? Still not getting any translations. 

If I run it like this myself, it does work:

    let s = NSBundle(forClass: object_getClass(self)).localizedStringForKey("Loading...", value: nil, table: "ParseUI")

but not when the similar code is run from within ParseUI. Am I doing something wrong, or does this not work as expected?

**Comment by nlutsenko** [comment]
The crucial piece here is the way you are integrating ParseUI.

If through a dynamic framework, which has a separate bundle (that method call to `NSBundle` will use a different path for the bundle) - to get this working simply put the ParseUI.strings file into `ParseUI.framework/$LOCALE.lproj/ParseUI.strings`.

If through a static framework - it should work out of the box with ParseUI.strings file inside your bundle, since all the code is going to be included in a single binary.

Let me know if this still doesn't work for you.

**Comment by ciryon** [comment]
I'm using dynamic frameworks, as it's the [recommendation from CocoaPods](http://blog.cocoapods.org/CocoaPods-0.36/). I'm not sure how to modify the ParseUI project and add my localization. My last resort is to create a fork, add the strings there and point my Podfile to use it.

**Comment by nlutsenko** [comment]
Fork works beautifully as well!
@ciryon are you translating into a specific language?
We can also add the localization in ParseUI itself! If that's the case - I am really looking forward to see a Pull Request! :grin:

**Comment by ciryon** [comment]
It's Swedish. I made a pull request here: https://github.com/ParsePlatform/ParseUI-iOS/pull/159

(though you may want to ponder if you want to accept it or not, I suppose it impacts other languages as well and involves future maintenance)
