### ISSUE TITLE
ParseUI won't compile for application extensions

### ISSUE THREAD

**Issue by ale0xB** [ParsePlatform/ParseUI-iOS#144]
I've installed ParseUI in my project using Cocoapods latest version (0.38.2), trying to use some classes (PFImageView) in my application extensions (a keyboard).

When trying to compile, it's giving me 3 errors 

``/Users/alexb/Projects/ParseUI-iOS/ParseUI/Classes/LogInViewController/PFLogInViewController.m:295:51: 'initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:' is unavailable: not available on iOS (App Extension) - Use UIAlertController instead.```

Same at ```PFQueryTableViewController``` and ```PFQueryCollectionViewController```

Also PFUIAlertView is unusable in App Extension, however [the compiler will silence these errors] (https://github.com/AFNetworking/AFNetworking/pull/2737#issue-78226228).

I think a good solution was adopted by AFNetworking guys, they made a macro available [AF_APP_EXTENSIONS](https://github.com/AFNetworking/AFNetworking/pull/265) so they discard on compile time whatever that  can't be used in app extensions. 

any thoughts on this?

**Comment by nlutsenko** [comment]
Hey @ale0xB, thanks for raising this. Indeed - we should support compiling for app extensions and marking APIs as unavailable in App Extensions is the way to go.
We already took this approach with [Parse SDK](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX), but we should update this one as well to do it.
