### ISSUE TITLE
Unnecessary email verification for Facebook login

### ISSUE THREAD

**Issue by acegreen** [ParsePlatform/ParseUI-iOS#154]
Hi,

I have implemented a PFLogInViewController with a Facebook and Twitter login.

For Facebook I extract their name and email and feed it into my currentUser. Because of the email, it sends out a verification email. Since Facebook already verified their emails, I think this is unnecessary. Email verification should be optional/disabled for Facebook and Twitter login.

On a side note:
1. How do I extract Twitter email addresses?
2. How to bypass the "I'm already authorized" when logging in through Facebook

**Comment by nlutsenko** [comment]
This is a great set of questions!

- There are 2 general ways to bail-out of email verification for an `email` field on a `PFUser`:
  - Disable email verification under your app settings on parse.com
  - Store email into a separate field that is called, say `verifiedEmail`

- Twitter email address:
  As far as I can tell - Twitter API restricts an ability to get user's email and requires whitelisting by Twitter.
  Source https://dev.twitter.com/rest/reference/get/account/verify_credentials

- `I'm already authorized` with Facebook. Can you give me an example, I am sorry, but I guess miss context here.

**Comment by acegreen** [comment]
Hello,

I appreciate the swift response :)

Email verification:
I needed email verification as I have a third option of authorizing through simple registration. I have disabled the third method and email authentication checks. Now just use Twitter and Facebook.

Twitter email address:
I'll look into whitelisting and that link. I thought Twitter was updating their rules to allow email without that.

Facebook authorization:
Sorry for the lack of context. Im implementing Facebook login through the Parse UI. I just activated the PFLogInFields.Facebook and added the required steps. Now every time I click that button, Parse opens a browser window (I think) WITHIN my app that either asks for authorization or tells me I already have it. So my question was how do I bypass that after the first authorization request?

Here's my code:

**Comment by acegreen** [comment]
Hello,

I appreciate the swift response :)

Email verification:
I needed email verification as I have a third option of authorizing through simple registration. I have disabled the third method and email authentication checks. Now just use Twitter and Facebook.

Twitter email address:
I'll look into whitelisting and that link. I thought Twitter was updating their rules to allow email without that.

Facebook authorization:
Sorry for the lack of context. Im implementing Facebook login through the Parse UI. I just activated the PFLogInFields.Facebook and added the required steps. Now every time I click that button, Parse opens a browser window (I think) WITHIN my app that either asks for authorization or tells me I already have it. So my question was how do I bypass that after the first authorization request?

Here's my code:

 func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

        // Initialize Facebook
        PFFacebookUtils.initializeFacebookWithApplicationLaunchOptions(launchOptions)

}

    func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
        
        return FBSDKApplicationDelegate.sharedInstance().application(application, openURL: url, sourceApplication: sourceApplication, annotation: annotation)
        
    }
        
func logInStatus() {
        
        if PFUser.currentUser() == nil {
            
            self.logInViewController = PFLogInViewController()
            self.signUpViewController = PFSignUpViewController()
            
            let logInLogoLabel: UILabel = UILabel()
            logInLogoLabel.text = "StockSwipe"
            logInLogoLabel.textColor = stockSwipeFontColor
            logInLogoLabel.font = UIFont(name: "HelveticaNeue", size: 45.0)
            
            let signUpLogoLabel: UILabel = UILabel()
            signUpLogoLabel.text = "StockSwipe"
            signUpLogoLabel.textColor = stockSwipeFontColor
            signUpLogoLabel.font = UIFont(name: "HelveticaNeue", size: 45.0)
            
            // PFLogInFields.UsernameAndPassword, PFLogInFields.LogInButton, PFLogInFields.SignUpButton, PFLogInFields.PasswordForgotten
            
            self.logInViewController.fields = [PFLogInFields.Twitter, PFLogInFields.Facebook]
            
            self.logInViewController.facebookPermissions = ["email"]
            
            self.logInViewController.logInView?.logo = logInLogoLabel
            self.signUpViewController.signUpView?.logo = signUpLogoLabel
            
            self.logInViewController.delegate = self
            self.signUpViewController.delegate = self
            self.logInViewController.signUpController = self.signUpViewController
            
            self.presentViewController(self.logInViewController, animated: true, completion: nil)
            
        } else {
            
            self.performSegueWithIdentifier("LoggedIn", sender: self)
            
        }
    }

func logInViewController(logInController: PFLogInViewController, didLogInUser user: PFUser) {
        
        if PFTwitterUtils.isLinkedWithUser(user) {
            
            print("Twitter login successful")
            
            let twitterUsername = PFTwitterUtils.twitter()!.screenName
            
            PFUser.currentUser()!.username = twitterUsername
            
            PFUser.currentUser()!.saveEventually(nil)
            
            self.logInViewController.dismissViewControllerAnimated(true, completion: { () -> Void in
                
                self.performSegueWithIdentifier("LoggedIn", sender: self)
                
            })
            
        } else if PFFacebookUtils.isLinkedWithUser(user) {
            
            print("Facebook login successful")
            
            // Get user email
            let accessToken = FBSDKAccessToken.currentAccessToken()
            if accessToken != nil {
        
                let req = FBSDKGraphRequest(graphPath: "me", parameters: ["fields":"email,name"], tokenString: accessToken.tokenString, version: nil, HTTPMethod: "GET")
                req.startWithCompletionHandler({ (connection, result, error : NSError!) -> Void in
                    
                    print(result)
                    
                    if error == nil {
                        
                        if let facebookEmail = result["email"] {
                            
                            PFUser.currentUser()!.email = facebookEmail as? String
                            
                        }
                        
                        if let facebookName = result["name"] {
                            
                            PFUser.currentUser()!.username = facebookName as? String
                            
                        }
                        
                        PFUser.currentUser()!.saveEventually(nil)
                    
                    } else {
                        
                        print("error \(error)")
                    }
                })
            }
            
            self.logInViewController.dismissViewControllerAnimated(true, completion: { () -> Void in
                
                self.performSegueWithIdentifier("LoggedIn", sender: self)
                
            })
            
        } else {
            
            logInController.presentViewController(displayAlert("Email Verification Required", message: "Please verify your email first using the email sent to you", Action1: okAlertAction, Action2: nil), animated: true, completion: nil)
            
            PFUser.logOut()
            
        }

**Comment by nlutsenko** [comment]
Facebook Auth:
I see... Afair FBSDK isn't going to open a web view in your app anymore, but rather try to switch you to Facebook.app and if that's not available - switch to Safari.

The thing is - you can't quite bypass that authorization request, as that is exactly the point when authorization happens. If you already have authorized the app - FB will forward the existing authorization, if you don't have it - after you approve it will pass the authorization. This behaviour applies to all apps using FB SDK, not just the ones that are built with ParseUI.

**Comment by acegreen** [comment]
- It doesn't try to switch me to the Facebook app nor does it take me to safari, it opens a safari view within my app.

- It then tells me I'm already authorized and I have two ways to dismiss that view. 
1. Through the ok button in which case it marks it as login complete
2. Through the done button (top right) in which case it doesn't mark as login complete. 

I think its something with my implementation. I tried a login on Tinder and it worked as expected. As I was already authorized, it didn't take me anywhere, just said logging me in and logged me in. Without taking me to Facebook app or Safari. 

When I remove authorization for Tinder and try to relog. it asks me to give it authorization through an alert view, and just logs me in. Again without going to Facebook or Safari.

**Comment by nlutsenko** [comment]
That one is actually probably using system authentication.
You can specify what kind of authentication you want to use by modifying `loginBehavior` property on `FBSDKLoginManager` (it's available under `PFFacebookUtils.facebookLoginManager()`)

**Comment by acegreen** [comment]
Ok will look into that as well. In the meantime lets go back to how I implemented it. I still have the web view open within my app and it always tells me I'm authorized.

Couldn't it take me to Facebook app or safari and immediately go back to my app without telling me I'm already authorized and expect me to press ok or done

**Comment by nlutsenko** [comment]
As far as I've seen - you can make it happen if you have logged in with Facebook in your system account. The `loginBehavior` option specifically controls how the authorization is performed, say by using only a system account first, or by switching to Safari.

**Comment by acegreen** [comment]
On a system level both my Facebook and Twitter accounts are added. With Twitter the button does as expected and shows me my account options and logs me in. Facebook opens browser within

Cn you show me an example of how to use loginBehavior. its not documented anywhere on Parse properly.

**Comment by nlutsenko** [comment]
It's not documented, because it's not related to Parse code at all, but rather an option of Facebook SDK :grin:

Something like this would work:
```swift
PFFacebookUtils.facebookLoginManager().loginBehavior = .SystemAccount
```
Add this before authenticating with Facebook, but after PFFacebookUtils are initialized.

**Comment by acegreen** [comment]
Ahh SOO beautiful :) works exactly as wanted when you have Facebook account in system.

When you don't, it opens that pesky webView, which is annoying because it has that done button top right which doesn't complete the login. You must click the ok under the you are already authorized. 

Didn't you say Facebook took that webView within app out?

**Comment by nlutsenko** [comment]
The web view option is still there, I am actually not sure why it doesn't transfer your app over to native app or Safari.
Quick question - do you have your url schemes setup properly in Info.plist?

**Comment by acegreen** [comment]
This is what I have:

<img width="468" alt="screen shot 2015-09-11 at 12 30 42 pm" src="https://cloud.githubusercontent.com/assets/10794609/9820304/fcdb5152-5880-11e5-84bb-975fd4786a68.png">

**Comment by nlutsenko** [comment]
This is the piece of code that controls this behavior:
https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.m#L344

I suggest opening an issue against `FBSDKLoginKit` to follow up on this so it's fixed for everyone at once.

**Comment by acegreen** [comment]
Somebody reported a similar issue with the "Done" button https://developers.facebook.com/bugs/1390559277910338/

**Comment by nlutsenko** [comment]
Sounds about right. I suggest subscribing to that issue at this point.
Also, you can always change the source of FBSDKLoginKit to fit your needs, so say - completely opt-out of WebView presentation and only do System->Native->Safari.

Let me know if there is anything else I can help you with.
(feel free to reopen this issue if I missed any points here)

**Comment by acegreen** [comment]
You have been more than helpful. 

By the way, how do I setup System->Native->Safari? and Native means I do the authentication? Technically I want System -> Safari

**Comment by nlutsenko** [comment]
You can adjust the code of FBSDKLoginKit locally to go do System, and if it fails or not available instead of using WebView - go Safari.

**Comment by acegreen** [comment]
Ohh i get it.

**Comment by acegreen** [comment]
By the way, is there a way to make the twitter and Facebook buttons above each other instead of side by side without setting the frame?

**Comment by acegreen** [comment]
@nlutsenko if i set PFFacebookUtils.facebookLoginManager().loginBehavior = .SystemAccount
it doesn't take the self.logInViewController.facebookPermissions = ["email"] into affect. I also asks for public profile which before just said email.

**Comment by nlutsenko** [comment]
AFAIU the system integration doesn't let you request for email address in this case, we definitely pass the permissions that you asked for from PFLogInViewController to FB API.

**Comment by acegreen** [comment]
it doesn't allow it? So it will always request the list of friends too?

Also can you take a look at the question above regarding layout of the buttons.

Many thanks

**Comment by ashish-naik** [comment]
@nlutsenko I have setup two Twitter accounts on my iPhone. App asks to select an account to login to and similar to above reported behaviour, i do not get email for the twitter account. I am successfully getting email on simulator for same account. I have not created system account.

I searched through PFTwitterUtils for similar method as Facebook to change login behaviour but could not find anything.

Is there an alternate?

Thanks 
Ashish
