### ISSUE TITLE
PFFile is not found

### ISSUE THREAD

**Issue by pronebird** [ParsePlatform/ParseUI-iOS#168]
I have the following configuration for a while now:

```
pod 'Parse', '~> 1.7.4'
pod 'ParseUI', '~> 1.1.4'
```

Got this:

```
/Pods/ParseUI/ParseUI/Classes/Views/PFImageView.m:26:9: 'Parse/PFFile.h' file not found
```

**Comment by nlutsenko** [comment]
Sounds super strange, since `Parse/PFFile` is definetly there.
Any chance you can update to the latest (1.8.5 for Parse and 1.1.6 for ParseUI)?

**Comment by pronebird** [comment]
Probably due:

[!] Can't merge user_target_xcconfig for pod targets: ["Realm", "Headers", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

That I get because of Realm/pop.

**Comment by nlutsenko** [comment]
Looks related, indeed...
We are not requiring specific `CLANG_CXX_LANGUAGE_STANDARD` setting, so I would suggest reporting this either in Realm or pop animation repo.

Let me know if there is anything else I can help you with!
