### ISSUE TITLE
How to implement a custom PFCollectionViewCell?

### ISSUE THREAD

**Issue by exalted** [ParsePlatform/ParseUI-iOS#170]
Having the source code at hand greatly helps debugging your own issues, but I couldn’t figure out how am I supposed to implement a custom `PFCollectionViewCell` overriding as little as possible in `PFQueryCollectionViewController` implementation.

I see `PFCollectionViewCell` defines `- (void)updateFromObject:(PFObject *)object` which will be called by the `PFQueryCollectionViewController` during `- (PFCollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath object:(PFObject *)object`, which is accurate; but then it seems `PFQueryCollectionViewController` will register `[PFCollectionViewCell class]` with `@"cell”` cell reuse identifier, hardcoded.

I guess at this point there’s no way to register another view cell type for `PFQueryCollectionViewController` unless we don’t override `- (void)loadView` in a subclass. For instance:

```swift
class MyCustomViewController: PFQueryCollectionViewController {
  override func loadView() {
    super.loadView()
    self.collectionView?.registerClass(MyCustomViewCell.self, forCellWithReuseIdentifier: “myCustomCell")
  }
}
```

This is _supposed_ to work, but it will also register `PFCollectionViewCell` because of `super.loadView()`. If we wanted to skip call to `super`, then it would be bad for at least two reasons:

1. it is good to call `super` when overriding life cycle functions, such as `loadView`
2. if we didn’t call `super`, we could have to implement again (a.k.a. copy & paste) all other logic that is left behind in `PFQueryCollectionViewController`’s `loadView` implementation.

Anyhow, at this point I was expecting to get back to my storyboard, setting custom class for my custom collection view cell to `MyCustomViewCell`,  “Collection Reusable View”’s identifier to `myCustomCell` and be done with it.

However…

In order to “test” it out, I overridden `updateFromObject` in `MyCustomViewCell`:

```swift
class EntryViewCell : PFCollectionViewCell {
  override func updateFromObject(object: PFObject?) {
    print("YAY!")
  }
}
```

And expecting it to print “YAY!” for every object, but haven’t got not even a single one.

What am I missing here? How are we supposed to implement a custom PFCollectionViewCell please?

Thank you,

**Comment by hhanesand** [comment]
What you did there won't work because the `-collectionView:cellForItemAtIndexPath:object:` method has the reuse identifier hardcoded in. Also, make sure the collection view is not nil in `loadView`.

You're going to want to override the `-collectionView:cellForItemAtIndexPath:object:` method so it loads the right cell, and then call `-updateFromObject:` on it.

**Comment by exalted** [comment]
:+1:
