### ISSUE TITLE
PFQueryTableViewController Paginated with estimatedRowHeight

### ISSUE THREAD

**Issue by lastMove** [ParsePlatform/ParseUI-iOS#171]
Hi, 

The pagination is not working well when using automatic dimensions cells. 
When tapping "load more" the tableView scrolls back to top.
To reproduce this, just add theses lines in the PaginatedTableViewController.swift file in the ParseUIDemo project.
```Swift
   override func viewDidLoad() {
        super.viewDidLoad()
        self.tableView.estimatedRowHeight = 20;
    }
```
Did someone has an idea about how to solve this?

**Comment by hhanesand** [comment]
If you're using auto-sizing cells, shouldn't you be setting `rowHeight` to `UITableviewAutomaticDimension` in `viewDidLoad` too?

**Comment by lastMove** [comment]
Yes, I try with it too. Still not working properly. 
I think that the problem is the same than this : 
http://stackoverflow.com/questions/25059443/what-is-nslayoutconstraint-uiview-encapsulated-layout-height-and-how-should-i

**Comment by lastMove** [comment]
Seems to be a weird bug. My workaround is that i will not use the built-in pagination system.
