### ISSUE TITLE
Crash try to log into Twitter account

### ISSUE THREAD

**Issue by wangbourne** [ParsePlatform/ParseUI-iOS#177]
When clicking the "Twitter button", crash happens with following errors:

2015-10-15 17:31:19.134 ParseUIDemo[3637:182765] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

To be highlighted, the project is directly from this repo and no changes are made except 
1. adding key/secret in didFinishLaunchingWithOptions
2. adding Facebook application ID in .plist

Update: crash happens when Twitter account hasn't been set in system setting

**Comment by wangbourne** [comment]
if there's no Twitter account set in system setting, crash happen after click "Twitter".

**Comment by nlutsenko** [comment]
Hey @wangbourne, we've seen couple reports about this so far.
Please double check in your app settings on Twitter Dev site that the 'Callback URL' is not empty.
This value will not be used by your iOS or Android application, but is necessary in order to enable authentication through Twitter.

**Comment by wangbourne** [comment]
You are right, thanks so much

**Comment by nlutsenko** [comment]
Glad it helped!

**Comment by mayankverma** [comment]
I have the value of callback_url configured and I am still seeing the same crash... However, I dont have twitter account setup on my phone but I dont think that should be necessary...

**Comment by nlutsenko** [comment]
@mayankverma, nope, shouldn't be necessary.
Can you post a stacktrace/more information about the crash that you are seeing?

**Comment by mayankverma** [comment]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x1829342d8 0x1946000e4 0x1828209c8 0x1828207f8 0x100fc2164 0x100fc5208 0x10117cfd4 0x10117cf94 0x101181c28 0x1828eb7f8 0x1828e98a0 0x1828152d4 0x18c26b6fc 0x187412f40 0x100173904 0x194caaa08)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by mayankverma** [comment]
its in line 

// Displays the web view dialog
- (BFTask *)_showWebViewDialogAsync:(NSString *)requestToken requestSecret:(NSString *)requestSecret {
    BFTaskCompletionSource *source = [BFTaskCompletionSource taskCompletionSource];

    static NSString *twitterAuthURLString = @"https://api.twitter.com/oauth/authenticate";

    PFOAuth1FlowDialog *dialog = [_oauthDialogClass dialogWithURL:[NSURL URLWithString:twitterAuthURLString]
                                                  queryParameters:@{ @"oauth_token" : requestToken }]; <=======

**Comment by nlutsenko** [comment]
Great. Can you please paste a stack trace?
Any chance you can check if `requestToken`/`requestSecret` are nil?

If they are nil and we didn't get the network error from the server - it means that twitter didn't give us proper values back.

**Comment by mayankverma** [comment]
yep seems like requestSecret is nil...

![screen shot 2015-10-19 at 3 47 49 pm](https://cloud.githubusercontent.com/assets/691038/10593467/dbe18776-7678-11e5-8303-e6d2f0a5b82b.png)

**Comment by mayankverma** [comment]
I was able to solve this issue but seems like this needs to be better handled... I deleted my twitter app and then recreated it again but I specified callback_URL at app creation time... previously, I added callback URL later... twitter may not have updated callback url in their DB which may have been resulting in crash above.. thanks
