### ISSUE TITLE
Compile error: include of non-modular header inside framework FBSDKLoginKit

### ISSUE THREAD

**Issue by wangbourne** [ParsePlatform/ParseUI-iOS#178]
see attached. Error happens on Xcode6.4 and Xcode7.
![compile error](https://cloud.githubusercontent.com/assets/2090084/10524474/60dfe4c8-73b2-11e5-8222-ffcdefd26293.jpg)

**Comment by nlutsenko** [comment]
Hey @wangbourne, thanks for the report.
This is a known issue inside FBSDKCoreKit/FBSDKLoginKit - being tracked here https://github.com/ParsePlatform/ParseFacebookUtils-iOS/issues/2
