### ISSUE TITLE
Facebook Login error on self.logInView.facebookButton tap

### ISSUE THREAD

**Issue by alessign** [ParsePlatform/ParseUI-iOS#186]
Hi, I was adding FB login to my app. I followed several tutorials and all code seems to be OK for iOS 9. I modified .plist for whitelisting FB, App ID & URL, updated frameworks, set keys and implemented code:

AppDelegate:

     [Parse setApplicationId:@"xxx"
                  clientKey:@"xxx"];
    
    [[FBSDKApplicationDelegate sharedInstance] application:application
                             didFinishLaunchingWithOptions:launchOptions];
    
    [PFAnalytics trackAppOpenedWithLaunchOptions:launchOptions];
    
    [PFFacebookUtils initializeFacebookWithApplicationLaunchOptions:launchOptions];

...

     - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                          openURL:url
                                                sourceApplication:sourceApplication
                                                       annotation:annotation];
     }

    - (void)applicationDidBecomeActive:(UIApplication *)application {
    [FBSDKAppEvents activateApp];
    if (![PFUser currentUser] && ![PFFacebookUtils isLinkedWithUser:[PFUser currentUser]]) {
        [self presentLoginControllerAnimated:NO];
    }
    }

...

      - (void)logInViewController:(PFLogInViewController *)controller didLogInUser:(PFUser *)user {
    
      FBSDKGraphRequest *request = [[FBSDKGraphRequest alloc] initWithGraphPath:@"me" parameters:nil];
      [request startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection, id result, NSError *error) {
        // handle response
        if (!error) {
            // handle result
            [self facebookRequestDidLoad:result];
        }
        else {
            [self showErrorAndLogOut];
        }
    }];
    }

And then in my login view controller:

     self.logInView.backgroundColor = [UIColor whiteColor];
     self.logInView.logo = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"logo"]];
     [self.logInView.facebookButton setTitle:@"Login with Facebook" forState:UIControlStateNormal];
     [self.logInView.facebookButton addTarget:self action:@selector(_loginWithFacebook) forControlEvents:UIControlEventTouchUpInside];
    
      [self _loadData];

...

     - (void)_loadData {
    // ...
     FBSDKGraphRequest *request = [[FBSDKGraphRequest alloc] initWithGraphPath:@"me" parameters:nil];
     [request startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection, id result, NSError *error) {
        if (!error) {
            // result is a dictionary with the user's Facebook data
            NSDictionary *userData = (NSDictionary *)result;
            
            NSString *facebookID = userData[@"id"];
            NSString *name = userData[@"name"];
            NSString *location = userData[@"location"][@"name"];
            NSString *gender = userData[@"gender"];
            NSString *birthday = userData[@"birthday"];
            NSString *relationship = userData[@"relationship_status"];
            
            NSURL *pictureURL = [NSURL URLWithString:[NSString stringWithFormat:@"https://graph.facebook.com/%@/picture?type=large&return_ssl_resources=1", facebookID]];
            
            // Now add the data to the UI elements
            // ...
        }
     }];
     }
     - (void)_loginWithFacebook {
     // Set permissions required from the facebook user account
     NSArray *permissionsArray = @[ @"public_profile", @"user_relationships", @"user_birthday", @"user_location"];
    
     // Login PFUser using Facebook
     [PFFacebookUtils logInInBackgroundWithReadPermissions:permissionsArray block:^(PFUser *user, NSError *error) {
        if (!user) {
            NSLog(@"Uh oh. The user cancelled the Facebook login.");
        } else if (user.isNew) {
            NSLog(@"User signed up and logged in through Facebook!");
        } else {
            NSLog(@"User logged in through Facebook!");
        }
      }];
     }
I also tried another method assigned to button's target:

      -(void)loginButtonClicked
     {
     FBSDKLoginManager *login = [[FBSDKLoginManager alloc] init];
     [login logInWithReadPermissions:@[@"public_profile"] handler:^(FBSDKLoginManagerLoginResult *result, NSError *error) {
        if (error) {
            NSLog(@"Process error");
        } else if (result.isCancelled) {
            NSLog(@"Cancelled");
        } else {
            NSLog(@"Logged in");
        }
      }];
    }

But in any case when I tap the fb log in button with target (_loginWithFacebook) I get this error:

     
![screen shot 2015-10-27 at 10 53 40](https://cloud.githubusercontent.com/assets/3117528/10756056/76c2a43e-7c99-11e5-93c7-c3ed9edbb45b.jpg)

fb log in button with target (loginButtonClicked) I get this error:

![screen shot 2015-10-27 at 10 54 08](https://cloud.githubusercontent.com/assets/3117528/10756081/9d951a9c-7c99-11e5-8628-99cf0189b8eb.jpg)

Can you please advice what is wrong in here?
Thank you

**Comment by alessign** [comment]
I forgot to add, that after tapping on the Facebook button, app crashes and it is not re-directing me to FB login

**Comment by lastMove** [comment]
It seems that you don't correctly add Facebook framework. 
You have to add it. Follow this https://parse.com/docs/ios/guide#users-facebook-users

**Comment by alessign** [comment]
Thanks, I ended up starting from scratch as I tried to update the frameworks by deleting them and dragging new ones. Clean project etc...it gave so many errors. So I downloaded latest frameworks and built new project with them. Seems to work fine now

**Comment by nlutsenko** [comment]
Glad you got it working...
This indeed looks like an issue with how you added Facebook SDK into your app.
