### ISSUE TITLE
Problem with Xcode 7.1

### ISSUE THREAD

**Issue by Casporro** [ParsePlatform/ParseUI-iOS#187]
I can't put the class with PFQueryTableViewController subclass on Interface Builder...

**Comment by nlutsenko** [comment]
Hey @Casporro, can you get us some more details on this?
Things like error codes/logs/screenshots would be very handy.

**Comment by Casporro** [comment]
Sorry... It was a newbie error... I was trying to put the class on UITableView not on UITableVIewController.
It would be nice a class like "PFTableView" besides "PFTableViewController".
Sorry for the inconveniences...
