### ISSUE TITLE
Creating a build ParseUI Framework for all devices & simulators

### ISSUE THREAD

**Issue by eranarbel** [ParsePlatform/ParseUI-iOS#19]
I'm interested in compiling the sources into a standalone universal framework (vs. including the ParseUI project in my workspace).

Unless I'm missing something, it seems that the included Workspace generates a framework file that is targeting arm7s (iPhone 5/5C)  & arm64 (5S and above), but not x86_64 and i386 (64 & 32-bit simulators).

Conversely, the framework file that is included in Releases page seems to include all architectures. Would be great to learn how to build this universal framework.

**Comment by spritesun** [comment]
Same issue here.

**Comment by nlutsenko-fb** [comment]
The script that is used to compile all 5 architectures inside a ParseUI.framework is quite simple:
You can get an idea on how it works here - https://github.com/BoltsFramework/Bolts-iOS/blob/master/scripts/build_framework.sh

Sub-project referencing (ParseUI.project in your Workspace) or using Cocoapods will generate the framework for the architectures you need at compile time. Including all 5 architectures, say when building for device - will generate 2 redundant slices that are never going to be used anyway.
Is there a specific use case that I missed, that you are trying to solve, guys?

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by nlutsenko-fb** [comment]
Feel free to reopen if the script in BoltsFramework is unclear or there is a use case that is missing...
