### ISSUE TITLE
Bitcode problem with XCode 7.1

### ISSUE THREAD

**Issue by flamesoft** [ParsePlatform/ParseUI-iOS#190]
I have updated to the Parse framework v1.9.1. But my app cannot be archived any more. It shows the following message:

ld: bitcode bundle could not be generated because '/Users/xx/Code/yyyy/ParseUI.framework/ParseUI(PFImageView.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I need to fix it and upload my app to the App Store. Is there any solution for this problem?

**Comment by flamesoft** [comment]
I disabled bitcode and got rid of the error during Archiving. My question is that if it is ok to work around like that.

**Comment by richardjrossiii** [comment]
Whoops! We're already tracking this bug here: #169. 

FWIW, I've found the issue in our project structure, and will have a fix in place for the next release.

**Comment by flamesoft** [comment]
Thanks !
