### ISSUE TITLE
Can't find aggregated framework

### ISSUE THREAD

**Issue by eugeniobaglieri** [ParsePlatform/ParseUI-iOS#207]
i modified some view controller inside the project, now i need to build Parse-UI and use ti in another project without cocoapods, but i can't find the final build that includes all architectures (device and simulator).

**Comment by nlutsenko** [comment]
Hey @eugeniobaglieri, there are 2 ways you can get the pre-compiled frameworks:
- Releases of this repository [here](https://github.com/ParsePlatform/ParseUI-iOS/releases)
- From [parse.com/docs/downloads](https://parse.com/docs/downloads)

Both of them contain ParseUI.framework in a precompiled form that includes all architectures (armv7, armv7s, arm64, i386, x86_64).

Let me know if this is what you are looking for.

**Comment by eugeniobaglieri** [comment]
I need to modify PFQueryTableViewController to add a feature and use this "custom" framework in my project

**Comment by nlutsenko** [comment]
Ah, I see...
Since we are fully relying on CocoaPods for the project - I would recommend using a plugin, say like https://github.com/neonichu/Rome

**Comment by eugeniobaglieri** [comment]
Great! Thank you!
