### ISSUE TITLE
Bug in PFSignUpView.h related to separator styles.

### ISSUE THREAD

**Issue by Ricardo1980** [ParsePlatform/ParseUI-iOS#21]
In this file:

https://github.com/ParsePlatform/ParseUI-iOS/blob/master/ParseUI/Classes/SignUpViewController/PFSignUpView.h

In all places that says UITextField should be PFTextField. That's the reason we cannot change the separator style properly. Well, it's possible something like:

    [self.signUpView.usernameField setValue:@(0) forKey:@"separatorStyle"];

But that's not nice.

(Similar case for UIButton and for PFLogInView)

To fix that, just change the class type to its actual type.
For instance:

@property (nonatomic, strong, readonly) UITextField *emailField;

Should be:

@property (nonatomic, strong, readonly) PFTextField *emailField;

**Comment by nlutsenko-fb** [comment]
Duplicate of #9
