### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RehaanA** [ParsePlatform/ParseUI-iOS#218]
ld: '/Users/rehaanadvani/Downloads/parse-library-1/Parse.framework/Parse(PFACL.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I get this error whenever I try to build my project. Is there an easy fix for this?

**Comment by nlutsenko** [comment]
Huh, this is strange. Did you download this from `parse.com`, also - could you confirm the version of the framework that you are trying to use. Also, another question on top - what is the version of Xcode you are using?

This problem shouldn't happen in the wild open, as we are including the bitcode slice.

**Comment by RehaanA** [comment]
Hi,

I just solved this problem by disabling bitcode in my Xcode project. I am using Xcode 7.2.

Thanks,
Rehaan

**Comment by nlutsenko** [comment]
Thanks. Yeah, that should help - but the problem shouldn't be there in the first place.
Going to confirm that we still have bitcode slice before closing this one out.

**Comment by nlutsenko** [comment]
Tested with the latest SDK download from both parse.com and releases page of SDK repo - bitcode is still there for iOS and it should work flawlessly.

@RehaanA, if you get a chance I suggest you trying to download the package from either [here](https://parse.com/downloads/ios/parse-library/latest) (parse.com) or [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/latest) (SDK repo).
