### ISSUE TITLE
How can I change separator color?

### ISSUE THREAD

**Issue by Ricardo1980** [ParsePlatform/ParseUI-iOS#22]
In the login and signup screen I see PFTextFileds that have gray separators.
Reading the code I see that it uses a class called UIColor and a method called textFieldSeparatorColor.

Can anyone explain me how I can change the separator color? I don't understand that approach.
Usually in these cases you implement the UIAppearance protocol or just show the color property. But in this library, I don't know what to do.

Thanks in advance.

**Comment by nlutsenko-fb** [comment]
Duplicate of #9
