### ISSUE TITLE
No packaged release for v1.2.0.

### ISSUE THREAD

**Issue by Bogidon** [ParsePlatform/ParseUI-iOS#234]
Any reason for [no precompiled framework for 1.2.0](https://github.com/ParsePlatform/ParseUI-iOS/releases/tag/1.2.0)?

**Comment by nlutsenko** [comment]
It's no longer going to be available on the releases page, as the intended installation flow is through CocoaPods. Though, you can still get it from https://parse.com/docs/downloads

Let me know if CocoaPods doesn't quite suit you and I'll get it back on the releases page.

**Comment by Bogidon** [comment]
I've been migrating away from CocoaPods to Carthage recently, so my best case scenario would be implementing #189. Not sure how used the downloads on the release pages for this project were... going to bet they weren't all that downloaded and I imagine it slows down your day to upload the SDK there.

I'm going to ask a question about Carthage in #189.

**Comment by lastMove** [comment]
Hi,
 i have the same issue. 
It would be nice to get it back on releases page.

**Comment by Xotic1** [comment]
I don't use CocoaPods or Carthage (you can blame my OCD :) ).  If someone could throw the .framework up here, I'd really appreciate it.

**Comment by JacobJT** [comment]
I'm also not interested in cocoa pods. Would appreciate a framework packaged with release.
