### ISSUE TITLE
Unsaved children are not able to be saved when updating parent object 

### ISSUE THREAD

**Issue by DanielsCode** [ParsePlatform/ParseUI-iOS#237]
I have a simple parse schema

Class AClass

    import Parse
    class AClass : PFObject, PFSubclassing {
      @NSManaged var title: String
      @NSManaged var childs: [BClass]?

      override class func initialize() {
        struct Static {
            static var onceToken : dispatch_once_t = 0;
        }
        dispatch_once(&Static.onceToken) {
            self.registerSubclass()
        }
      }

       static func parseClassName() -> String {
        return "AClass"
      }
    }

Class BClass

     import Parse
     class BClass : PFObject, PFSubclassing {
      @NSManaged var message: String

       override class func initialize() {
         struct Static {
             static var onceToken : dispatch_once_t = 0;
        }
        dispatch_once(&Static.onceToken) {
            self.registerSubclass()
        }
      }
      static func parseClassName() -> String {
        return "BClass"
      }
    }

AppDelegate.swift

     BClass.registerSubclass()
     AClass.registerSubclass()

ViewController.swift e.g. I tried ...

        let query = AClass.query()
        query?.includeKey("BClass")
        query?.getFirstObjectInBackgroundWithBlock({ (parent, error) -> Void in
            if error == nil {
                let parentObj = parent as? AClass
                parentObj.childs?.last?.message = "Changed"
                parentObj.saveInBackground()
            } else {
                print("Error: \(error)")
            }
        })

I thought that parse would save recursive. First the parent object and all changed child objects. But I can't see any changes in the parse dashboard of the message field (BClass).

I am using Parse (1.12.0) . Any ideas?

**Comment by nlutsenko** [comment]
Looks like you are using `includeKey` on a class name, instead of a field, which makes the mutation of a message on a last element in childs array a no-op.

Try changing `query?.includeKey("BClass")` to `query?.includeKey("childs")`.

**Comment by DanielsCode** [comment]
You are right .... I prepared as simple demo and did a mistake. Unfortunately the fix doesn't work. Here is my updated sample code - ViewController:

        let query = AClass.query()
        query?.includeKey("childs")
        query?.getFirstObjectInBackgroundWithBlock({ (parent, error) -> Void in
            if error == nil {
                let parentObj = parent as? AClass
                print("current Message 1: \(parentObj?.childs?.last?.message)")
                parentObj?.childs?.last?.message = "Changed"
                parentObj?.saveInBackgroundWithBlock({ (success, error) -> Void in
                    if success {
                        let query = AClass.query()
                        query?.includeKey("childs")
                        query?.getFirstObjectInBackgroundWithBlock({ (parent, error) -> Void in
                             if error == nil {
                                let parentObj = parent as? AClass
                                print("current Message 2: \(parentObj!.childs?.last?.message)")
                             } else {
                                print("Error: \(error)")
                            }
                        })
                    } else {
                        print("Error: \(error)")
                    }
                })
            } else {
                print("Error: \(error)")
            }
        })
 
Console Log:

    current Message 1: Optional("Start")
    current Message 2: Optional("Start")

Any ideas?

**Comment by DanielsCode** [comment]
It's maybe the same issue as in the JS-DSK? see [https://github.com/ParsePlatform/Parse-SDK-JS/issues/89](url)

**Comment by DanielsCode** [comment]
I just recognised that I put this issue in the wrong context: ParseUI-iOS. I will close this and open a new issue in Parse-SDK-iOS-OSX. Sorry for any inconvenience.
