### ISSUE TITLE
Display links to privacy policy and term of uses in sign up view

### ISSUE THREAD

**Issue by chengyin** [ParsePlatform/ParseUI-iOS#32]
Currently the UI does not provide any ability display privacy policy or term of use. 

AppStore requires those for distribution, and I think as part of the ParseUI, the PFSignUpView needs to support those.

**Comment by nlutsenko-fb** [comment]
This is definitely a good thing to display in a PFSignUpView.

An example simple customization that you could apply to get it inside your app:
- subclass PFSignUpView and add a UI element
- add `layoutSubviews` in your subclass of PFSignUpView to place the new UI element accordingly
- subclass PFSignUpViewController
- overload `loadView` in your subclass of PFSignUpViewController with custom initialization for _signUpView with a different class

I think specifics of this addition will vary too much for different apps - making it a specific customization that you can apply on top of ParseUI and not something existing by default.
Feel free to reopen the issue and/or send a pull request for this one.
