### ISSUE TITLE
PFSignUpViewController sign up with Facebook

### ISSUE THREAD

**Issue by msuprovici** [ParsePlatform/ParseUI-iOS#36]
It would be great if PFSignUpViewController had a PFSignUpFieldsFacebook option in a similar way PFLogInViewController has the PFLogInFieldsFacebook option.

**Comment by nlutsenko-fb** [comment]
Hey, thanks for the request,

Actually, for logging in with services like Facebook or Twitter - there is no need in signup, as if the user didn't exist before - it will be created automatically.
There is more information about how it works in this guide 
https://parse.com/docs/ios_guide#fbusers-signup/iOS

**Comment by msuprovici** [comment]
Yes I understand.  According to the docs, there are cases when you want separate log-in and sign-up views, hence the PFSignUpViewController.  But if I just wanted to present the PFSignUpViewController, I can't give the user a sign in with facebook option unless I present them PFLogInViewController first with the PFLogInFieldsSignUpButton option.  

It would be nice to have a sign up with facebook option available in the PFSignUpViewController to communicate to the user that they are creating an account with facebook.  Check out the sign up view for Spotify:

![spotify](https://cloud.githubusercontent.com/assets/4229720/5902232/a81a05ca-a52d-11e4-8d97-d14c33df4ff9.PNG)
