### ISSUE TITLE
PFQueryCollectionViewController not fetching PFObjects in Swift

### ISSUE THREAD

**Issue by sheharyar-rr** [ParsePlatform/ParseUI-iOS#38]
I have implemented it and initialized it this way 
    required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        self.parseClassName = "userPhoto";
        self.pullToRefreshEnabled = true
        self.paginationEnabled = true
        self.loadingViewEnabled = true
    }

objectsDidLoad method is reporting nil as error and objects as nil too. Also i have tried to set the view controller's user defined run time attribute of parseUserClass = "userPhoto" but it hasn't helped. Nothing is showing up or being fetched.

**Comment by nlutsenko-fb** [comment]
Are you using Storyboards or XIBs by any chance?

**Comment by sheharyar-rr** [comment]
Storyboards. Same class in objective-C works with storyboards.

**Comment by nlutsenko-fb** [comment]
Thanks for confirmation!

I am going to try to reproduce this with Storyboards in Swift, though I am still unsure about it being a specific Swift thing and a general concept of not supporting Storyboards in a direct fashion.

**Comment by emrecaliskan** [comment]
Ok, So I'm quite new to iOS development bot for me the issues arise (just like the previous comments), when storyboards are used in Swift. I managed to at least get the very basic functionality working without storyboards but then had difficulties customizing my custom PFCollectionViewCell, simply due to inexperience in doing so without the storyboard. 

I was looking at PFQueryTableViewController, and I'm wondering whether it's because the: 
 
"(instancetype)initWithCoder:(NSCoder *)decoder" and "(instancetype)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil " 

methods aren't implemented, as they are implemented in PFQueryTableViewController. I may be complete mistaken here, but just trying to to figure things out myself.

**Comment by jccf091** [comment]
I am able to fetch PFObjects in Swift with this:
```swift
   required convenience init(coder aDecoder: NSCoder) {
      self.init(className: "Post")
      loadingViewEnabled = true
      pullToRefreshEnabled = true
      paginationEnabled = true
      objectsPerPage = 25
      loading = true
    }
    override init!(collectionViewLayout layout: UICollectionViewLayout!, className: String!) {
      super.init(collectionViewLayout: layout, className: className)
    }
    convenience init(className:String!) {
      var layout = UICollectionViewFlowLayout()
      self.init(collectionViewLayout: layout,className: className)
    }
```


But when I do this: 
```swift
    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath, object: PFObject) -> PFCollectionViewCell! {    
      var cell: PFCollectionViewCell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath, object: object) as PFCollectionViewCell {
      var post = object as Post
      cell.imageView.imageURL = NSURL(string: post.lowResolutionImageURL)
      return cell
  }
```
all the images was displayed at random position.
I am also looking for a way to custom the PFCollectionViewCell.

**Comment by nlutsenko-fb** [comment]
By "displayed at random position" - could you share a screenshot/preview of what you expect and what you get?

`imageView.imageURL` - I believe this is something custom happening there, as neither UIImageView, nor PFImageView declare that property.

**Comment by nlutsenko-fb** [comment]
Hey guys,

#39 contains a demo project for using PFQueryCollectionViewController with Storyboards.
Let me know if it helps you get going further...

**Comment by sheharyar-rr** [comment]
The problem i was having originally with using PFQueryCollectionVC with objC+storyboards was that it wasn't fetching the right pictures, and there are repeating pictures. Not just that but each time i scroll down and scroll back up, i see different pictures in different positions.
