### ISSUE TITLE
"Load More..." label is in the wrong place after loading a second page

### ISSUE THREAD

**Issue by dreese** [ParsePlatform/ParseUI-iOS#42]
1. Clone repo
1. Run `pod install`
1. Open workspace
1. Open `PaginatedCollectionViewController.m`
1. Set `objectsPerPage` to 2 instead of 10 (on line 40)
1. Run the `ParseUIDemo` project
1. Tap on "Paginated Collection row.
1. Tap on the "Load more..." several times
1. The location of the "Load more..." view never moves.

I expected that the "Load more..." view would always be at the bottom of the collection view, at the end of the last loaded page. However, it always remains in the position it was first loaded at. Later pages are loaded right on top of the "Load more..." view.

**Comment by dreese** [comment]
If I comment out lines 270 and 276, then it works properly.
```
- (UICollectionReusableView *)collectionViewReusableViewForNextPageAction:(UICollectionView *)collectionView {
//    if (!_nextPageView) {
        _nextPageView = [collectionView dequeueReusableSupplementaryViewOfKind:UICollectionElementKindSectionFooter
                                                           withReuseIdentifier:PFQueryCollectionViewNextPageReusableViewIdentifier
                                                                  forIndexPath:[self _indexPathForPaginationReusableView]];
        _nextPageView.textLabel.text = NSLocalizedString(@"Load more...", @"Load more...");
        [_nextPageView addTarget:self action:@selector(loadNextPage) forControlEvents:UIControlEventTouchUpInside];
//    }
    _nextPageView.animating = self.loading;
    return _nextPageView;
}
```

**Comment by dreese** [comment]
I'd be happy to submit a pull request, but wasn't sure that just commenting stuff out wouldn't break something else. Let me know if I can help.

**Comment by nlutsenko-fb** [comment]
You are absolutely right! UICollectionView wants a new view, as it will not reposition the existing one...

**Comment by dreese** [comment]
Thanks!
