### ISSUE TITLE
Login with Facebook hang upon return from authorization

### ISSUE THREAD

**Issue by chamroeunbm** [ParsePlatform/ParseUI-iOS#49]
Hi,
I use Facebook login popup. After returning from Facebook app or Facebook website after authentication,  the login popup just hangs, i can't receive any input or even close (x).

**Comment by nlutsenko-fb** [comment]
Hey @chamroeunbm, thanks for reporting this...

Unfortunately, without a repro - I am not sure if there is anything actionable, as simply running through the login flow in included ParseUIDemo - everything seems to work.

Feel free to reopen with a repro or more details for us to act on or file a bug report at https://parse.com/help
