### ISSUE TITLE
image center always pinned to upper left of UIImageView in PFCollectionViewCell

### ISSUE THREAD

**Issue by pukeanddie** [ParsePlatform/ParseUI-iOS#50]
I'm working with the PFQueryCollectionViewController and it seems like the contentMode on the PFImageView objects in the PFCollectionViewCell isn't set correctly when loading large images. When I try to manually set contentMode to aspectFill the images aren't displaying at all.

**Comment by nlutsenko-fb** [comment]
Hey @pikeanddie, thanks for the report!

There was a recent fix in #40, where it adapts the contentMode to the size of the image.
I would recommend checking out the version of ParseUI from master, and if it does not help - I am not sure if there is a way to proceed without a repro/screenshots...

**Comment by pukeanddie** [comment]
ok, yes, I bet that is my issue. I'm pulling from cocoapods which, I guess, is not pulling from master?

**Comment by nlutsenko-fb** [comment]
Yes, it is pulling from the latest tag - which is a little behind latest master.
Closing the issue, as it seems to be already resolved.
