### ISSUE TITLE
PFQueryTableViewController Local Datastore

### ISSUE THREAD

**Issue by lightice11** [ParsePlatform/ParseUI-iOS#53]
Just checking to make sure I did not miss anything but PFQueryTableViewController does not have support for the Local Datastore functionality correct?

**Comment by nlutsenko-fb** [comment]
Hey @lightice11,

PFQueryTableViewController and PFQueryCollectionViewController should definitely work with Local Datastore.
Is there anything specific that you are looking for or anything that prevents you from using it with Local Datastore?

**Comment by lightice11** [comment]
So the PFQueryTableViewController does or does not support Local Datastore "out of the box"? Maybe my question was unclear but I know I can modify it to support it but I was just making sure that I wasn't duplicating functionality.

I'm pretty new to parse, so it may be that I'm not completely understanding how the Local Datastore works just yet.

**Comment by nlutsenko-fb** [comment]
>So the PFQueryTableViewController does or does not support Local Datastore "out of the box"?

What are you looking for specifically? 
What kind of OOB support you think is missing? (PRs are more than welcome)
  
  
To make PFQueryTableViewController query Local Datastore you would need to subclass it, overload a `query` method to return results from Local Datastore - but the following applies to any custom-built query for PFQueryTableViewController, like adding more constraints/ordering/etc...

It would look something like:
```objc
- (PFQuery *)query {
  PFQuery *query = [super query];
  return [query fromLocalDatastore];
}
```

**Comment by lightice11** [comment]
Yes, I'm aware of how I can modify the PFQueryTableViewController to support it, specifically how to make it first fetch results from the Local Datastore and then from Parse.

Perhaps the confusion here is coming from the fact that I don't completely understand what the `cachePolicy` property on PFQuery is or does. The documentation in the header file suggests that it can not be used while pining is enabled, which leads me to believe that it has nothing to do with the Local Datastore.

If I look at previous examples of code that was introduced before the local datastore was available, they implement caching by setting the `cachePolicy` to `kPFCachePolicyCacheThenNetwork` which causes the query to first check the cache (not the local datastore?) and then the main parse server. It seems illogical to me that the introduction of the Local Datastore should prevent the usage of the `cachePolicy` as is saves the user the trouble of making 2 queries, one for the Local Datastore (`[query fromLocalDatastore]`), and then another one for the network.

Perhaps you can elaborate on what the `cachePolicy` is and whether or not it has anything to do with the Local Datastore or not?

**Comment by nlutsenko-fb** [comment]
`cachePolicy` is indeed could only be used without Local Datastore. Query caching adds ability to make 2 queries: against the local cache (if any) and against Parse - to fetch the latest data. And `cachePolicy` is simply an option that gives you the ability to determine which logic to use for an instance of `PFQuery`.

Local Datastore on the other hand is not cache, but rather a persistent storage for your objects.
With Local Datastore is enabled - you can decouple your View and Controller/Model logic and have PFQueryTableViewController always show results from Local Datastore (e.g. from a specific pin), whilst independently load the new results from network and pin them with the same name as you've used for PFQueryTableViewController.

I hope this makes sense...

**Comment by lightice11** [comment]
Ok, that makes sense. Thanks for the clarification. If I am happy with the system I end up building for the cache querying, I will submit a pull request or maybe open a new issue.

**Comment by tartur** [comment]
Hi,

I have almost the same requirement as @lightice11. I store for each user all its mandatory objects with saveEventually, that way I end up with better tolerance to network issues.
In the other hand, most of the time I have to read the data from the local datastore then from Parse, this enhances at least UX to avoid making him waiting for remote query when he has the relevant objects locally. I created a helper method that looks like the following
```swift
class func findObjectsLocallyThenRemotely(query: PFQuery!, block:[AnyObject]! -> Void) {
        let localQuery = (query.copy() as PFQuery).fromLocalDatastore()
        localQuery.findObjectsInBackgroundWithBlock({ (locals, error) -> Void in
            if(error == nil) {
                block(localObjects)
            } else {
                Log.error("Local Query", msg: "\(query.parseClassName) failed", error: error)
            }
            query.findObjectsInBackgroundWithBlock({ (objects, error) -> Void in
                if(error == nil) {
                    PFObject.unpinAll(localObjects)
                    block(objects)
                    PFObject.pinAllInBackground(objects, block: { (success, error) -> Void in
                        if !success {
                            Log.error("Pin Query Result", msg: "\(query.parseClassName) failed", error: error)
                        }
                    })
                }
            })
        })
    }
```
So I had the same question about PFQueryTableViewController, is there any way that I can override the query mechanism to run it once on the local datastore and then with a remote call ?

**Comment by lightice11** [comment]
I ended up making a subclass of the PFQueryTableViewController that overrides the `loadObjects:clear:` function. First it loads data from the local datastore and updates the internal tableview and then it fetches from the network. It then compares the 2 arrays of information to figure out whether to update - the internal tableview again. Here is a [gist you can compare with](https://gist.github.com/lightice11/3747430b18d12c94fffe). (I'm using [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa) so if you need help deciphering the code, I'd be happy to help)
