### ISSUE TITLE
really hard time setting background views and subviews

### ISSUE THREAD

**Issue by hsavit1** [ParsePlatform/ParseUI-iOS#62]
my subviews dont show up and my background views will not change color. 

ive tried with loginView and signUpView and they both are broken

**Comment by nlutsenko-fb** [comment]
Hey, thanks for the report...
Can you get a little bit of more details on what is that you are trying to do and what is broken?
It's quite hard to identify the issue from this report.

Also I would suggest looking at https://github.com/ParsePlatform/ParseUI-iOS/blob/master/ParseUIDemo/Classes/CustomViewControllers/LogInViewController/CustomLogInViewController.m and generally at ParseUIDemo, as there is a lot of examples on how to modify style and usage for all the UI components.

Feel free to reopen this issue/open a different one. ;)

**Comment by hsavit1** [comment]
I have been working with parse for a long time, I know how to use the classes

Im working with Parse iOS SDK version 1.6.1, so please tell me if any of these bugs have been fixed in later versions

Here are my issues: on the PFLoginViewController, when I add subviews to the logInView they become unresponsive. I added a button to the logInView as a subview and the button RARELY responds when I tap on it ! Very weird behavior. I've come to the conclusion that the only thing that could be screwing up the behavior has been Parse. 
Unrelated, on the PFLogInViewController, I tried changing the tintcolor of the forgot password button to [UIColor whiteColor] and that had no effect

Now for the PFSignUpViewController: when I try to change the backgroundColor to anything, it is impossible. So I set the backgroundColor with a tiled image instead... fine. But where I am really having issues is I cant get the dismiss button to show up. Idk why but it just won't show. Yes I've check the fields. It is included as one of the acceptable fields. 
I've tried adding a UIButton as a subview and that hardly works also. I was getting the same behavior as what was happening with the PFLoginViewController. The button image didnt show up, and the button was hardly responsive. Maybe 1 in 30 taps went through

**Comment by hsavit1** [comment]
I am using objective c
