### ISSUE TITLE
Broken layout in PFCollectionViewCell when using image with PFFile.

### ISSUE THREAD

**Issue by pronebird** [ParsePlatform/ParseUI-iOS#63]
Hi,

I have a subclass of PFQueryCollectionViewController that I instantiate via Storyboard. I use ParseUI 1.1.1 since previous version had a bug or lack of support for `initWithCoder:`.

The problem is that PFCollectionViewCell does not layout imageView. Image view inside is PFImageView which I gladly give a PFFile.

This is in subclass of collection cell:

```objc
- (void)updateFromObject:(PFObject*)object {
    Post* post = (Post*)object;
    
    self.imageView.file = post.photoForCurrentDevice;
    [self.imageView loadInBackground];
}
```

My collection view data source looks similar to what PFQueryCollectionVC offers:

```objc
- (PFCollectionViewCell*)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath object:(PFObject *)object {
    PostCollectionCell* cell = [collectionView dequeueReusableCellWithReuseIdentifier:@"Cell" forIndexPath:indexPath];
    
    [cell updateFromObject:object];
    
    return cell;
}
```

All of these methods are verified to be called and all subclasses are properly set. Image is loaded but according to UI debugger the frame for PFImageView in custom cell is {0,0,0,0}.

Apparently if I call `setNeedsLayout` on cell then it works:

```objc
    [self.imageView loadInBackground:^(UIImage* image, NSError* error) {
        [self setNeedsLayout];
    }];
```

Wouldn't be better to use Autolayout or simply stretch image view on the whole size of cell? I (believe) it should not be the case then.

**Comment by nlutsenko-fb** [comment]
Hey @pronebird,

Stretching to the full size - that's an option.
Using auto-layout - not sure how that would work out, but that's also an option.

Current layout code (as you might have seen in PFCollectionViewCell class) will dynamically change how image is laid out in a cell, based on the image size. 
In addition, if you load an image into a generic UIImageView - it would actually have a similar problem, as `superview` doesn't know that the image changed. Calling `setNeedsLayout` I would say is somewhat required here.

What do you think? I would love to hear your suggestions (PRs as well) on how we can improve this.

**Comment by pronebird** [comment]
If I recall it correctly, the problem with using PFFile is that I don't really have a callback for that until I use Bolts task but that is not much convenient. It wouldn't be much of a problem if image view had some reasonable layout mask or constraints set.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by hallucinogen** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
