### ISSUE TITLE
Crash caused by nil supplementary element

### ISSUE THREAD

**Issue by dreese** [ParsePlatform/ParseUI-iOS#66]
The documentation from Apple for the `
- collectionView:viewForSupplementaryElementOfKind:atIndexPath:` method says:

> Return Value
> A configured supplementary view object. You must not return nil from this method.

Parse's code for this method is:
```
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView
           viewForSupplementaryElementOfKind:(NSString *)kind
                                 atIndexPath:(NSIndexPath *)indexPath {
    if ([self _shouldShowPaginationView] &&
        [kind isEqualToString:UICollectionElementKindSectionFooter] &&
        [indexPath isEqual:[self _indexPathForPaginationReusableView]]) {
        return [self collectionViewReusableViewForNextPageAction:collectionView];
    }
    return nil;
}
```

I believe that this method must always return an object. We are seeing a crash caused, apparently, by this method returning nil at times:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the view returned from -collectionView:viewForSupplementaryElementOfKind:atIndexPath (UICollectionElementKindSectionFooter,<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}) was not retrieved by calling -dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath: or is nil ((null))'

Since the Parse code looks like it is calling the proper dequeue method (from the `collectionViewReusableViewForNextPageAction:` method), I assume the crash is caused by returning nil.

I'll see if I can find more exact repro steps.

**Comment by dreese** [comment]
Re-reported here:
https://developers.facebook.com/bugs/1426694127626707/

**Comment by nlutsenko-fb** [comment]
Awesome. Thank you. 
It would be super helpful if you've attached a repro project to the bug.

**Comment by dreese** [comment]
It's very rare for us. I will try. The docs are pretty clear that returning a nil from that method will cause a crash. Is there a reason to continue returning nil there?

**Comment by nlutsenko-fb** [comment]
This must have changed or there is probably a use case where it's called, but it shouldn't.
As specified in documentation: `If you do not want a supplementary view in a particular case, your layout object should not create the attributes for that view.`
If the layout specifies zero size for the supplementary view - this method should not be called.

**Comment by dreese** [comment]
Yeah, it's certainly possible that it's an iOS bug too. There are many. :)

I tried to reproduce the crash for about 30-45 minutes, and cannot. I will try some more, but if I can't get something more concrete, then maybe we can just close it.

**Comment by dreese** [comment]
I am still trying to repro this one.

**Comment by dreese** [comment]
I am unable to find repro steps, and we haven't had any reports from the field either. Let's go ahead and close this. I will re-open or re-submit if I see this again. Thanks for looking!

**Comment by obibring** [comment]
I may be missing something, but `collectionViewReusableViewForNextPageAction:` should return a `UICollectionReusableView *` obtained via `dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath:` (as per the error message). How is the child class implementation of `collectionViewReusableViewForNextPageAction` supposed to invoke said dequeueing method without access to `indexPath`?

**Comment by nlutsenko** [comment]
@obibring good point... Do you mind creating a separate issue for it?
It does indeed need an indexPath - we would need to publicize an API for it in order to not break any existing API users.
Something like `indexPathForPaginationReusableView` would fit and we already have it internally...

**Comment by dreese** [comment]
As a note, I still see this issue very occasionally. I just cannot get any useful repro steps. Perhaps the `indexPath` will help.

**Comment by dreese** [comment]
I created #96 for that issue.

**Comment by dreese** [comment]
In our last release, we made a change that drastically increased the number of these crashes. We have two solid repro steps within our app that trigger the crash 100% of the time. We have received 276 reports in just 2 weeks.

We fixed the crash by altering the method as follows:
```
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView
           viewForSupplementaryElementOfKind:(NSString *)kind
                                 atIndexPath:(NSIndexPath *)indexPath {
    return [self collectionViewReusableViewForNextPageAction:collectionView];
}
```

This is consistent with Apple's docs that say that method should never return nil.

I understand that there is likely a bug somewhere else that is causing that method to be called when it shouldn't be (in the layout, likely) but that doesn't seem like a good reason to leave known-bad code in place.

I am going to try to create a simple repro project and send in a pull request.

**Comment by nlutsenko** [comment]
Thanks! That would be super helpful!

**Comment by dreese** [comment]
When catching this error, it looks like `[self _shouldShowPaginationView]` returns `NO` because `self.objects.count` is zero.

**Comment by nlutsenko** [comment]
Right... Then `collectionView:layout:referenceSizeForFooterInSection` will also return `CGSizeZero`.
I guess all it is is that it is not using the constraint on this method to return or not to return the footer, but rather wants the view for footer at all times.

**Comment by dreese** [comment]
Yes, I checked the collection view's flow layout property for `footerReferenceSize`, which was `CGSizeZero` too. We must be doing something weird.

**Comment by dreese** [comment]
I think it has something to do with using `JDFPeekabooCoordinator`. We have one `JDFPeekabooCoordinator` that manages several `PFQueryCollectionView`s by switching the `scrollView` property. `JDFPeekabooCoordinator` intercepts delegate calls. Might be our fault that the delegate calls are getting re-directed somehow.

**Comment by nlutsenko** [comment]
Closing this one out as the PR merged in.
Not sure if that one is what causing the issue, but am really curious to hear how your search goes.

**Comment by dreese** [comment]
Thanks for the update. After reconfiguring our code, I can no longer reproduce the original crash. I still don't know why exactly, but I believe it had something to do with the delegates of the PFQueryCollectionViewController subclass getting messed up by that other library we were using. We are still using it, but in a different way, and the crash seems to be gone.

I think the pull request changes are still a good direction—you've got `referenceSizeForFooterInSection:` working properly. Thanks again!
