### ISSUE TITLE
PFQueryTableViewController loads infinitely when set to custom cell

### ISSUE THREAD

**Issue by SharkyZg** [ParsePlatform/ParseUI-iOS#67]
Without this code data is fetched into TableView:

override func tableView(tableView: UITableView!,cellForRowAtIndexPath indexPath: NSIndexPath!, object: PFObject!) -> PFTableViewCell! {
        let cell = tableView.dequeueReusableCellWithIdentifier("Cell") as TableViewCell

        cell.trackingNumber.text = object["trackingNumber"] as String
        
        return cell
        
    }

With this code nothing happens except loading screen. I have red tons of posts today and I believe that something happened with new Xcode/Swift version because I don't see any other reason why this shouldn't work.

I have specified "Cell" as identifier in storyboard and subclassed PFTableView (TableViewCell). I get no errors from compiler.

**Comment by ericcgu** [comment]
```Swift
override func tableView(tableView: UITableView!, cellForRowAtIndexPath indexPath: NSIndexPath!, object: PFObject!) -> PFTableViewCell! {
        let cell = tableView.dequeueReusableCellWithIdentifier(kCellIdentifier, forIndexPath: indexPath) as! PFTableViewCell
  
        if let trackingNumber = object["trackingNumber"] as? String {
            cell.textLabel?.text = trackingNumber
        }
        return cell
    }
}
```

Notice how I unwrapped and used PFTableViewCell.

Follow me on Twitter: @ericguuu

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by hallucinogen** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by polis80cy** [comment]
I am afraid this still exists with the latest release. Please see for details:

http://stackoverflow.com/questions/34986817/cant-display-custom-cell-with-pfquerytableviewcontroller-swift2
