### ISSUE TITLE
Delete rows in PFQueryTableViewController

### ISSUE THREAD

**Issue by pronebird** [ParsePlatform/ParseUI-iOS#71]
Please, add option to remove objects in `PFQueryTableViewController`. Right now I have to reload the whole table instead of dropping single row.

**Comment by ericcgu** [comment]
+1

**Comment by nlutsenko-fb** [comment]
I think it's possible via adding a method to delete an object in a query, so we can optimistically update the table.

**Comment by ericcgu** [comment]
@nlutsenko-fb you are the man. Looking forward to it.

**Comment by pronebird** [comment]
Iirc we just need a method to delete an object in objects array, we can delete PFObject ourselves.

**Comment by stanleyw** [comment]
We agree this is a great feature request, but need to focus on some bug fixes inside the SDK in the short term.  We'll get back to this!

**Comment by nlutsenko** [comment]
Should be implemented by #98

**Comment by nlutsenko** [comment]
Released with ParseUI 1.1.4
