### ISSUE TITLE
No such module ParseUI

### ISSUE THREAD

**Issue by macpraveen** [ParsePlatform/ParseUI-iOS#73]
I added `pod 'ParseUI'` and installed. But when I use `import ParseUI` I get no such module error whereas it works for `import Parse`.

Now I am currently using the packaged ParseUI.framework to overcome this issue.

What is the solution for this?

**Comment by nlutsenko-fb** [comment]
Looks like Cocoapods on your end is installing ParseUI as a library, not as a framework.
Libraries don't have clang modulemaps - so in Swift code you can't simply `import ParseUI`.
There are 2 solutions for this: `use_frameworks` option available in Cocoapods, or add `#import <ParseUI/ParseUI.h>` to your ObjC bridging header.

**Comment by macpraveen** [comment]
I updated cocoapods to 0.36.1 and used `use_frameworks!` option but now I get the following error.

>The target has transitive dependencies that include static binaries: (/..../Pods/Parse/Parse.framework and /..../Pods/ParseFacebookUtils/ParseFacebookUtils.framework)

Any help?

**Comment by nickswalker** [comment]
I had success adding the import to the bridging header and running a Clean.

**Comment by macpraveen** [comment]
Yes I'm able to use bridging header as well. But use_frameworks! option not working. Another issue which I'm facing is Xcode is unable to autocomplete ParseUI headers in bridging header file. I do not know whether this is an Xcode bug or anything with ParseUI. But able to build with manually typing the headers.

**Comment by vladimircezar** [comment]
@macpraveen Did you solve this? 
I have the same problem here.

**Comment by macpraveen** [comment]
It works with bridging header as mentioned in my previous comment.
