### ISSUE TITLE
Cannot install 'pod ParseUI' with 'use_frameworks!'

### ISSUE THREAD

**Issue by eneko** [ParsePlatform/ParseUI-iOS#76]
Given the following Podfile:
```
platform :ios, '8.0'
use_frameworks!

pod 'Facebook-iOS-SDK'
pod 'Parse', '~> 1.7.1'
pod 'ParseUI', '~> 1.1.3'
```

I get the following error:
```
[!] The 'Pods' target has transitive dependencies that include static binaries: ([...]/Pods/Parse/Parse.framework)
```

'Parse' pod can be installed properly from source when using frameworks for Swift, but ParseUI cannot, because it has a direct dependency on 'Parse.framework'. This could be solved if ParseUI pod depended on Parse pod instead.

**Comment by ray-** [comment]
:+1:

**Comment by doronkatz** [comment]
Was there a solution for this? Or way around it? Does the latest --pre version resolve this?

**Comment by eneko** [comment]
Yes, this is still an issue.  'pod Parse' can be installed properly, it is just ParseUI that fails, because of the static binary dependencies.

**Comment by nlutsenko-fb** [comment]
Hey guys,

Just wanted to let you know that we are on it and looking to find a solution for this issue.
In the meantime - the workaround is to use downloadable Parse SDK from https://parse.com/docs/downloads

**Comment by felipelc** [comment]
:+1:

**Comment by felipelc** [comment]
Hello guys,

I'm trying to solve, but I'm a beginner at cocoapods world. But I found some discussions about the same problem at Google Map SDK. Maybe this can help someone more experienced:
https://github.com/CocoaPods/CocoaPods/issues/2943#issuecomment-69473672
http://stackoverflow.com/questions/28405079/linker-errors-in-a-swift-project-with-google-maps-for-ios-added-via-cocoapods/28471830#28471830

**Comment by ericcgu** [comment]
Why not try Carthage as dependency manager?

**Comment by nlutsenko-fb** [comment]
Hey everyone,

I just pushed the new Parse SDK release (1.7.2) that should fix the problem.
Tested with `use_frameworks!` on ParseUI project and ParseUI podspec validation - everything looks great and works now.

Please reopen this issue if it didn't help in your case.

**Comment by bre7** [comment]
Everything is working fine when I use an old project, but when I create a new one (Swift, SingleView, everything default) the same message described above appears:
>Installing ParseUI (1.1.3)
[!] The 'Pods' target has transitive dependencies that include static binaries: (/.../Pods/Parse/libParse.a)
Failed with exit code: 1


Podfile
>source 'https://github.com/CocoaPods/Specs.git'

>platform :ios, '8.0'
use_frameworks!

>inhibit_all_warnings!

>pod 'Parse',                    '~> 1.7'
pod 'ParseUI',                  '~> 1.1'
