### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by ericcgu** [ParsePlatform/ParseUI-iOS#78]
query.cachePolicy = .CacheElseNetwork

![screen shot 2015-04-09 at 6 04 10 pm](https://cloud.githubusercontent.com/assets/4943759/7077963/080421a2-dee3-11e4-8463-770d6d622506.png)

**Comment by ericcgu** [comment]
https://twitter.com/ericguuu/status/585608217339760640

**Comment by nlutsenko-fb** [comment]
Fixed and live!
Thanks for pointing this out!
