### ISSUE TITLE
The login error message is misleading and cannot be customized

### ISSUE THREAD

**Issue by yllan** [ParsePlatform/ParseUI-iOS#79]
I use PFLoginViewController. When I type the incorrect username, the error message is:

"The operation couldn't be completed. (NSURLErrorDomain error -1011.)"

Although I can use delegate method to handle the error and give a user-friendly message, there is no way to prevent the "The operation couldn't be completed" alert from showing up.

**Comment by nlutsenko-fb** [comment]
Actually - you can tweak the source of ParseUI and override it, but I agree that this is somewhat misleading and we should do better here.

**Comment by stanleyw** [comment]
Released in ParseUI-iOS 1.1.4 :)
