### ISSUE TITLE
Redefinition of 'PFCachePolicy' in Xcode 6.3, using Cocoapods

### ISSUE THREAD

**Issue by ndbroadbent** [ParsePlatform/ParseUI-iOS#80]
I'm getting these errors coming from ParseUI, but in the Parse `PFConstants.h` header. They just started happening, so it might just be a problem in my project.

Any idea why this is happening? Maybe `PFConstants.h` needs to check if it's been imported twice?

![screenshot 2015-04-15 22 40 17](https://cloud.githubusercontent.com/assets/139536/7162742/88b91776-e3c0-11e4-929c-872f0d612f8b.png)

**Comment by ndbroadbent** [comment]
Sorry, I ran `rm -rf Pods; pod install` and the problem went away. Must have messed up my cocoapods somehow.

**Comment by ndbroadbent** [comment]
Oh, I just realized that I did a search and replace in my project to update the PFCachePolicy constants for Swift 1.2. I accidentally replaced all the occurrences in the Parse headers. Sorry!

**Comment by Claus79** [comment]
which version was it? I run into this problem after updating to version 0.39.0 and the library giving me this error is SDWebImage

**Comment by ericjsalazar** [comment]
Is there any update on how to fix this bug? I cannot find this anywhere else.
