### ISSUE TITLE
Possibility to change loginView?

### ISSUE THREAD

**Issue by brunocascio** [ParsePlatform/ParseUI-iOS#83]
```
/*!
 @abstract The log in view. It contains all the enabled log in elements.
 @see PFLogInView
 */
@property (PFUI_NULLABLE_PROPERTY nonatomic, strong, readonly) PFLogInView *logInView;
````

Change property to `@property (PFUI_NULLABLE_PROPERTY nonatomic, strong) PFLogInView *logInView;
`
is bad idea?

I want to customize view with other views, for example add a slider. Actually it's added with code,  but is more difficult rather than using storyboards or xibs files.

I will like to use this:

```
//instantiate login controller
CCLoginControlllerViewController *logInController = [[CCLoginControlllerViewController alloc] init];
logInController.logInView = [storyboard instantiateViewControllerWithIdentifier:@"login"];
```  

**CCLoginControlllerViewController** is subclass for **PFLoginViewController** and  `[storyboard instantiateViewControllerWithIdentifier:@"login"];` instantiate an view from storyboard.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by hallucinogen** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
