### ISSUE TITLE
Facebook login Button problem

### ISSUE THREAD

**Issue by brunocascio** [ParsePlatform/ParseUI-iOS#84]
Hi!

I try to change title of facebookLogin button, but doesn't work. My code:

```
[self.logInView.facebookButton setTitle:@"Ingresar con Facebook" forState:UIControlStateNormal];
[self.logInView.facebookButton setTitle:@"Ingresar con Facebook" forState:UIControlStateHighlighted];
[self.logInView.facebookButton setTitle:@"Ingresar con Facebook" forState:UIControlStateReserved];
[self.logInView.facebookButton setTitle:@"Ingresar con Facebook" forState:UIControlStateSelected];
[self.logInView.facebookButton setTitle:@"Ingresar con Facebook" forState:UIControlStateDisabled];
```

Result:

![captura de pantalla 2015-04-21 a las 13 10 35](https://cloud.githubusercontent.com/assets/2397875/7256841/db045f20-e827-11e4-8afc-64a69d0873d3.png)

But, when press button, it change to "Ingresar con facebook". I don't understand... UIControlStateNormal not work?

**Comment by nlutsenko-fb** [comment]
It does work - but as you can probably see from Source Code - it is going to change the title multiple times and simply setting a different text manually doesn't always work.

There are 2 ways I see we can take here - add another localization for this button (which will help everyone) or make it respect outside setters for title and do not change the title at that point.

@brunocascio, what do you think?

**Comment by brunocascio** [comment]
Tomorrow I will try what you say :)

**Comment by nlutsenko-fb** [comment]
:ok:

**Comment by brunocascio** [comment]
I'm back.
I missed a detail. The login view, is embedded. The reason it worked was because the title was not assigned to the corresponding event.

solution:

```
-(void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    
    [self.logInView.facebookButton setTitle:@"Ingresar con Facebook" forState:UIControlStateNormal];
}
```

Thanks @nlutsenko-fb !
