### ISSUE TITLE
Error installing ParseUI pod with Cocoapods 0.37

### ISSUE THREAD

**Issue by bre7** [ParsePlatform/ParseUI-iOS#86]
When I create a new project (Swift, SingleView, everything default) the same message described in #76 appears:
>Installing ParseUI (1.1.3)
[!] The 'Pods' target has transitive dependencies that include static binaries: (/.../Pods/Parse/libParse.a)
Failed with exit code: 1

Podfile
>source 'https://github.com/CocoaPods/Specs.git'

>platform :ios, '8.0'
use_frameworks!

>inhibit_all_warnings!

>pod 'Parse',                    '~> 1.7'
pod 'ParseUI',                  '~> 1.1'

**Comment by felipelc** [comment]
Same thing happens to me after I update to cocoapods 0.37. When I downgrade to cocoapods 0.36.4 everything works fine.

**Comment by minikin** [comment]
@felipelc thank you for your tip.

**Comment by bre7** [comment]
Indeed felipe. There are issues like this one (regarding v0.37) in CP's github: https://github.com/CocoaPods/CocoaPods/issues

**Comment by nlutsenko** [comment]
Hey guys,

Just wanted to let you know that we are aware of this platform and looking for a way to fix it.
In the meantime, as a workaround - you can downgrade to previous release of Cocoapods.

**Comment by nlutsenko** [comment]
Hey guys,

I just pushed the fixed podspec to Cocoapods and it works like a charm on both 0.36.4 and 0.37.
This is fixed now - go run `pod update` to get the new 1.7.2.2 Parse pod.
