### ISSUE TITLE
Styling PFTextField separators

### ISSUE THREAD

**Issue by jaybayley** [ParsePlatform/ParseUI-iOS#9]
Hi guys, really nice job on the refreshed Login/Signup views, much cleaner and more inline with the latest  iOS versions.

I'm not sure if this is obvious and i'm just missing something, but I can't figure out how to style the separator colours on the various PFTextField's (usernameField, passwordField etc).

I'm trying to style the Login/Signup forms to use a dark theme, but the separators seem fixed to a very light grey/white colour. Any help would be hugely appreciated.

![parse](https://cloud.githubusercontent.com/assets/754748/5170238/18e9edc8-7406-11e4-8ad7-3bd75dc4d1ce.png)

**Comment by Ricardo1980** [comment]
I opened a related bug: #21
