### ISSUE TITLE
Change pullToRefresh image

### ISSUE THREAD

**Issue by brunocascio** [ParsePlatform/ParseUI-iOS#93]
It's possible?

**Comment by nlutsenko** [comment]
Pull to refresh in PFQueryTableViewController / PFQueryCollectionViewController is just a generic `UIRefreshControl` and could be customized as any other `UIRefreshControl` :)
Read more on it here -> https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIRefreshControl_class/index.html

Let me know if this helps :)

**Comment by brunocascio** [comment]
Thanks! :)
