### ISSUE TITLE
Running login platform specific code when didLogInUser is called

### ISSUE THREAD

**Issue by AlexanderNorway** [ParsePlatform/ParseUI-iOS#94]
Hello. I originally asked this question as a follow up question on the parse google group on April 4th, but I have yet to receive an answer.

I have two different pieces of code for retrieving user info from either Twitter or Facebook and saving it to the user on Parse the first time didLogInUser is called depending on which button was used to log in. How can I know which button the user clicked to run the correct 3rd party login platform specific code?

**Comment by nlutsenko** [comment]
Both `PFTwitterUtils` and `PFFacebookUtils` have `isLinkedWithUser()` method.
After the user logged in - you can use it against `PFUser.currentUser()` to get information whether one or the other log in method was used.

**Comment by nlutsenko** [comment]
Let me know if this doesn't help. :)

**Comment by AlexanderNorway** [comment]
Thank you for helping! I will try this when I get home from work. Thanks! :)

**Comment by AlexanderNorway** [comment]
Yeah, thanks! That worked.
