### ISSUE TITLE
Login via Facebook works but empty token

### ISSUE THREAD

**Issue by BabyAzerty** [ParsePlatform/ParseUI-iOS#95]
I have updated my app with the latest Facebook SDK (v4) as well as Parse 1.7.2 and ParseUI 1.1.3

The login (PFLogInViewController) works - I don't see any visual error, everything goes smoothly. I have a current user with PFUser but I don't have any token with FBSDKAccessToken.

So every time I try to read the user's basic info, I can't as there is no token.

This is what I request `loginController.facebookPermissions = ["public_profile", "user_friends"]`
And this is the Facebook error 

    error =         {
            code = 2500;
            message = "An active access token must be used to query information about the current user.";
            type = OAuthException;
        };

**Comment by timbrah** [comment]
+1

**Comment by nlutsenko** [comment]
Hey guys, there is a new release of the SDK from today.
Any chance you can test the same thing with it? (There was a bug fix closely related to this issue).

Let me know here if it helps or not.

**Comment by BabyAzerty** [comment]
1.7.3 repairs the problem of the Facebook token. But creates a new problem: Parse Crash Report is not functional anymore...

**Comment by timbrah** [comment]
Thanks @nlutsenko. I was using the Parse SDK's via cocoapods and it was not updated to the latest version. Are the cocoapods versions maintained, or are the SDK's only managed as direct downloads from Parse?
