### ISSUE TITLE
Not possible to call loadObjects on PFQueryTableViewController anymore

### ISSUE THREAD

**Issue by sarbogast** [ParsePlatform/ParseUI-iOS#99]
Since I upgraded my CocoaPods dependency to ParseUI 1.1.4, I'm not able to call loadObjects on PFQueryTableViewController from its subclass anymore. Yet, the loadObjects method is still declared in the header file. Any idea what might be causing this. Note that my PFQueryTableViewController subclass is written in Swift and this method does not compile anymore:

    override func viewWillAppear(animated: Bool) {
            super.viewWillAppear(animated)
            self.loadObjects()
    }

**Comment by sarbogast** [comment]
I figured it out. I had forgotten to import Bolts/Bolts.h in my bridging header, and as the method now returns a BFTask, it was not visible. Now that I added `#import <Bolts/Bolts.h>` to my bridging header, everything is back to normal.

**Comment by prometheon** [comment]
This fixed my issue also. Thanks!
